// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOriyJ3vfCH0cHmqSVvI-oQOkcpiC6HQg',
    appId: '1:261238166615:web:4d091e3a5f2b1fdf643f12',
    messagingSenderId: '261238166615',
    projectId: 'corpcom-77651',
    authDomain: 'corpcom-77651.firebaseapp.com',
    databaseURL: 'https://corpcom-77651-default-rtdb.firebaseio.com',
    storageBucket: 'corpcom-77651.appspot.com',
    measurementId: 'G-ZN7NQQF3TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjL28Ynnl0wmEddUqV9X9ov3a6M5-cFAw',
    appId: '1:261238166615:android:51f02ce1272f12d5643f12',
    messagingSenderId: '261238166615',
    projectId: 'corpcom-77651',
    databaseURL: 'https://corpcom-77651-default-rtdb.firebaseio.com',
    storageBucket: 'corpcom-77651.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs3nZaQYnA7M6wq-5B3EA_gU-IymfqKGc',
    appId: '1:261238166615:ios:0612b90f30d53925643f12',
    messagingSenderId: '261238166615',
    projectId: 'corpcom-77651',
    databaseURL: 'https://corpcom-77651-default-rtdb.firebaseio.com',
    storageBucket: 'corpcom-77651.appspot.com',
    iosClientId: '261238166615-a5sv7ljv6n44mdlm5t69jo3u5kgmhul7.apps.googleusercontent.com',
    iosBundleId: 'com.example.corpCom',
  );
}
